### ISSUE TITLE
Plugin not listed in the plugin store

### ISSUE THREAD

**Issue by heedfull** [PederBirk/Flow.Launcher.Plugin.MediaControl#1]
This plugin does exactly what I want to do, pause and play music without using the mouse. Thanks for writing it. It would be great if it is easier for others to be able to use it easily. Adding it to the plugin store will allow this.

**Comment by PederBirk** [comment]
Hello, and thank you for you interest in this project. I don't use FlowLaucher as much any more, since I work mostly on Linux these days, but would be happy to have this listed on the store if it is of use to others.

**Comment by PederBirk** [comment]
Pull request for PluginsManifest here: https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/351

**Comment by PederBirk** [comment]
Plugin is now available in the store
